spring:
  profiles:
    active: dev

---
server:
  port: 9000

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost::3306/tale
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      reset-stat-enable: false
      stat-view-servlet:
        login-username: admin
        login-password: password

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false

mybatis:
    type-aliases-package: com.lcy.tale.model.entity
    mapper-locations: classpath:mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
